resource "local_file" "inventory" {
  content = <<-DOC
    # Ansible inventory containing variable values from Terraform.
    # Generated by Terraform.

---
all:
  hosts:
    minikube-node-01:
      ansible_host: ${yandex_compute_instance.minikube.network_interface.0.nat_ip_address}

  
  children:
    prod:
      children:
        minikube:
          hosts:
            minikube-node-01:
      
  vars:
    ansible_connection_type: paramiko
    ansible_user: dotsenkois
    DOC
  filename = "../playbook/inventory/prod/hosts.yml"
  

  depends_on = [
    yandex_compute_instance.minikube,
  ]
}
