version: '3.1'
services:
  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: neto_pgdb
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .PG/data:/var/lib/postgresql/data
      - .PG/bkp:/var/lib/postgresql
    ports:
      - "5432:5432"