apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  namespace: stage
spec:
  containers:
  - name: nginx
    image: nginx:latest
    env:
    - name: SECRET_USERNAME
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: user
          optional: false # same as default; "mysecret" must exist
                          # and include a key named "username"
    - name: SECRET_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: password
          optional: false # same as default; "mysecret" must exist
                          # and include a key named "password"
    ports:
    - containerPort: 443
      protocol: TCP

    volumeMounts:
    - name: certs
      mountPath: "/etc/nginx/ssl"
      readOnly: true
    - name: config
      mountPath: /etc/nginx/conf.d
      readOnly: true


  volumes:
  - name: certs
    secret:
      secretName: nginx-cert
  - name: config
    configMap:
      name: nginx-config
  