{
 "title": "Node stats",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Количество места на файловой системе",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes/(1024*1024*1024)"
    }
   ]
  },
  {
   "title": "CPULA 1/5/15",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load1" },
    { "expr": "node_load5" },
    { "expr": "node_load15" }
   ]
  },
  {
   "title": "Количество свободной оперативной памяти",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_memory_MemFree_bytes" }
   ]
  },
  {
   "title": "Утилизация CPU для nodeexporter ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 * (rate(node_cpu_seconds_total{mode=\"system\"}[1m]))"
    }
   ]
  }
 ]
}