---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: logreader-role
  namespace: app-namespace
rules:
  - apiGroups: [ "" ]
    resources: [ "pods" ]
    verbs: [ "get", "list", "describe", "watch" ]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: logreader-clusterrole
  namespace: app-namespace
rules:
  - apiGroups: [ "" ]
    resources: [ "pods" ]
    verbs: [ "get", "list", "describe", "watch" ]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: logreader
  namespace: app-namespace
subjects:
- kind: User
  name: logreader
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: logreader-role
  apiGroup: rbac.authorization.k8s.io
