apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: logreader
spec:
  signerName: kubernetes.io/kube-apiserver-client
  request: ${BASE64_CSR}
  usages:
  - digital signature
  - key encipherment
  - client auth