---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: logreader
  namespace: app-namespace
rules:
  - apiGroups: [ "" ]
    resources: [ deployments ]
    verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: logreader
rules:
  - apiGroups: [ "" ]
    resources: [ deployments ]
    verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: logreader
  namespace: app-namespace
subjects:
- kind: User
  name: logreader
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io