---
apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "logreader" to read pods in the "app-namespace" namespace.
# You need to already have a Role named "pod-reader" in that namespace.
kind: RoleBinding
metadata:
  name: logreader
  namespace: app-namespace
subjects:
# You can specify more than one "subject"
- kind: User
  name: logreader # "name" is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: Role #this must be Role or ClusterRole
  name: logreader # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io