{{ $namespace := .Values.namespace }}
{{- range .Values.deployment }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ $namespace }}
  name: {{ .name }}
  labels:
    app: {{ .name }}
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      containers:
        - name: {{ .name }}
          image: {{ .containers.image }}
          ports:
          - containerPort: {{ .containers.ports.containerPort }}
            protocol: TCP
          env:
          {{- range .containers.env }}
            - name: {{ .name }}
              value: {{ .value }}
          {{ end }}
{{- end }}