apiVersion: v1
kind: Service
metadata:
  namespace: {{.Values.namespace }}
  name: {{ .Values.deployment.backend.name }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.deployment.backend.service.type }}
  ports:
    - port: {{ .Values.deployment.backend.service.port }}
      targetPort: 9000
      protocol: TCP
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}

