#cloud-config
ssh_pwauth: no
users:
  - name: dotsenkois
    sudo: ALL=(ALL) NOPASSWD:ALL
    #shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCk/KrPNXmRFqgjGi749CoRZOH3eP3ODXGNF6C8ObflQmxzVenc2uz02sjPiChjQo+OEWSIZX+y29MvJn0/nJ/s12NaxSTsaZ6ew8hXZ0rLR4BFyML3SUUCrstByq8r3REAUTAvyzvdWsJL0Fs0eP3Rx/L5UeJeQQUUOWzBQvjkGbsivO03Mup0pfVqmk3vwbi4izxXmRpX7NTFhMY9dr3IObKXcuNsG5BOfrRYGssZlkajmh9MFe57Wna3jrGcld7YYDqT2Pt7h9tS4sLRv0m95VIq9cpq/d5b4i+A+Ps8qpowGvEb2B6N6eCpLcifJlF0aHhQN9U3oHzFFHyIchNETWzUZLDC9YbTOVexohQtEoB0VG7l8mIe3+NQCfy2hSj9Yr3kWf+1z5L1gBfjbOMm1fNkRHUVDvqKEUohjQyGzhbGIoiCq1hnQTmV9r+BA8FFH2ZShNg9Ru+PQ0pJNI8dZXVWWoxwMAYpK80kl+Fat77yA+g+e4TPEJ+n190fIBk= dotsenkois@debian
