resource "local_file" "inventory" {
  content = <<-DOC
    # Ansible inventory containing variable values from Terraform.
    # Generated by Terraform.

---
all:
  hosts:
    jenkins-master-01:
      ansible_host: ${yandex_compute_instance.jenkins-master.network_interface.0.nat_ip_address}
    jenkins-agent-01:
      ansible_host: ${yandex_compute_instance.jenkins-agent.network_interface.0.nat_ip_address}
  children:
    jenkins:
      children:
        jenkins_masters:
          hosts:
            jenkins-master-01:
        jenkins_agents:
          hosts:
              jenkins-agent-01:
        # nexus:
        #   hosts:
        #     nexus-01:
      
  vars:
    ansible_connection_type: paramiko
    ansible_user: dotsenkois
    DOC
  filename = "../infrastructure/inventory/cicd/hosts.yml"
  

  depends_on = [
    yandex_compute_instance.jenkins-master,
    yandex_compute_instance.jenkins-agent,
    # yandex_compute_instance.nexus
  ]
}
