---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-backend
  namespace: stage
  labels:
    app: frontend-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-backend
  template:
    metadata:
      labels:
        app: frontend-backend
    spec:
      containers:
      - name: frontend
        image:  dotsenkois/kuber_frontend
        ports:
        - containerPort: 80
      - name: backend
        image: dotsenkois/kuber_backend
        ports:
        - containerPort: 9000

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-backend
  namespace: stage
spec:
  ports:
    - name: frontend
      port: 8000
      targetPort: 80
    - name: backend
      port: 9000
      targetPort: 9000
  selector:
    app: frontend
  type: ClusterIP
