---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "new_chart.fullname" . }}
  labels:
    {{- include "new_chart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.deployment.frontend.autoscaling.enabled }}
  replicas: {{ .Values.deployment.frontend.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "new_chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.deployment.frontend.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "new_chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.deployment.frontend.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "new_chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.deployment.frontend.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.deployment.frontend.securityContext | nindent 12 }}
          image: "{{ .Values.deployment.frontend.image.repository }}:{{ .Values.deployment.frontend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.deployment.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.deployment.frontend.resources | nindent 12 }}
      {{- with .Values.deployment.frontend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.frontend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.frontend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
